dist: bionic
language: python
addons:
  firefox: latest
services:
  - xvfb
python:
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - openssl aes-256-cbc -K $encrypted_39a259669b29_key -iv $encrypted_39a259669b29_iv -in deploy_id_rsa.enc -out deploy_id_rsa -d
install:
  - pip3 install -r requirements.txt
script:
  - cd instagram
  - python3 manage.py migrate
  - pytest -vvv --flake8
deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: script
  script: cd ..; fab deploy -i deploy_id_rsa
