version: '3'

services:
  django:
    image: docker.pkg.github.com/qwanysh/django_instagram/django_instagram
    command: bash -c 'python3 instagram/manage.py collectstatic --noinput && python3 instagram/manage.py migrate && cd instagram && gunicorn -c gunicorn.conf instagram.wsgi'
    volumes:
      - ./gunicorn.conf:/src/instagram/gunicorn.conf
      - ./static:/src/instagram/static
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    depends_on:
      - django
    environment:
      - TZ=Asia/Almaty
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"